### ISSUE TITLE
Often Unstable when I test only three node 

### ISSUE THREAD

**Issue by Mingwei-Gu** [IBM/SpectrumScale_NETWORK_READINESS#10]
Here is the data, node2 and node3 is in the same gateway, testtime is 60s:
test1
Host,Throughput MB/sec
node1,10800
node2,4250
all at the same time,9590
node3,11100
test2
Host,Throughput MB/sec
node1,11000
node2,11000
all at the same time,11600
node3,11000
test3
Host,Throughput MB/sec
node1,3500
node2,11100
all at the same time,10900
node3,11000
test4
Host,Throughput MB/sec
node1,11000
node2,10900
all at the same time,8960
node3,11000

But, when I use preftest tool - ib_write_bw, it shows that the network environment is stable.

**Comment by bolinches** [comment]
Hi

Not sure where you get the above but 60 seconds is not how the tool run so it would not be with this tool. If you have any comments or issues about your results, I recommend to open a service request with IBM or whoever is the OEM that resells ECE to you. Issues here are for the tool itself, not for specific results if they pass or not the KPIs
