### ISSUE TITLE
Can you provide a example of nsdperftool.py syntax use? I am getting an error when trying to execute the program

### ISSUE THREAD

**Issue by gacaaviIBM** [IBM/SpectrumScale_NETWORK_READINESS#13]
Hello, Koet.py is working good but I want to only run perftool, however i am not sure on how to make it work, so far I am receiving the following error:

[root@gabriel-node-mgr SpectrumScale_NETWORK_READINESS]# ./nsdperfTool.py --client gabriel-node-1 --server gabriel-node-mgr
2023-07-13_06:18:53: MainThread: CMD: ip addr show
Traceback (most recent call last):
  File "./nsdperfTool.py", line 526, in <module>
    localNode = getLocalNode(allNodes)
  File "./nsdperfTool.py", line 238, in getLocalNode
    rc, ipaddr_output, ec = runcmd("ip addr show")
  File "./nsdperfTool.py", line 427, in runcmd
    [out, err] = p.communicate(timeout = int(conf["ttime"]) + timerWindow)
ValueError: invalid literal for int() with base 10: 

Any help would be appreciated

**Comment by bolinches** [comment]
Hi

It never been the idea of this to use only a underlying subset of this. It was designed modularly to have multiple tests (latency and throughput now) in a modular way centralized for automation and human consumption from the koet (a Finnish word loosely translated as tests or experiences) script.

Having said that if you really want only to run throughput, just comment the latency calls at koet .. bonus if you add a paremeter and a pull request for doing exactly that; and maybe another one for doing only latency as it is a massive killer of performance. We simulated latencies on same environments when we came up with the KPI for ECE and 1.0 to 2.0 ms gives you near half the performance

I am going to close this one as it is not being used as designed nor a problem of the koet path
