### ISSUE TITLE
koet.py does not handle duplicate packets when testing throughput

### ISSUE THREAD

**Issue by cristeab** [IBM/SpectrumScale_NETWORK_READINESS#3]
This is the error I am seeing when testing with 21 nodes:

Starting many to many nodes throughput test
Completed many to many nodes throughput test
Traceback (most recent call last):
  File "./koet.py", line 1994, in <module>
    main()
  File "./koet.py", line 1948, in main
    hosts_dictionary)
  File "./koet.py", line 1315, in load_multiple_fping
    mean_all.append(str(mean_list(latencies_list)))
  File "./koet.py", line 1111, in mean_list
    list = [float(lat) for lat in list]  # we convert them to float
  File "./koet.py", line 1111, in <listcomp>
    list = [float(lat) for lat in list]  # we convert them to float
ValueError: could not convert string to float: 'duplicate'

**Comment by bolinches** [comment]
Hi thanks for the finding. Could you please add the data inside the log directory for this run? If you do not want to share it publicly due IPs or other information please send me a private message. Thanks

**Comment by bolinches** [comment]
Going to close due inactivity, if you can reproduce and upload the logs, lets reopen then.
