### ISSUE TITLE
Confuse about flow direction

### ISSUE THREAD

**Issue by Mingwei-Gu** [IBM/SpectrumScale_NETWORK_READINESS#7]
When I test throughput, on koet.py, there is a hint "run from node1 to all nodes". But in nsdperf.C, server node run "rdmaWrite". In fact, the flow direction is "all nodes to node1". May I know why distribution is like this?

**Comment by bolinches** [comment]
It simulates node "1" is the client and the rest are NSD servers. Idea is to test the capabilities of that node and the net on that node

I do not see this as a bug. But pls care to expand and we see.
