### ISSUE TITLE
When I change thread number to 2, it doesn't work

### ISSUE THREAD

**Issue by Mingwei-Gu** [IBM/SpectrumScale_NETWORK_READINESS#8]
As title, I changed nsdperfTool.py's inputs from "-R 32 -W 32 -T 32" to "-R 2 -W 2 -T 2", it doesn't work.

**Comment by bolinches** [comment]
Works as design you are only to use koet that for now does not expose that and other features. Consider those backend tools, not to be used. 

Feel free to add taht feature. What are you trying to achieve by adding more threads? Pls remember this is not a substitute of nsdperf but a easy to use and read results and compare results, so limits the options
